export default {
  name: "AccordionItem",
  summary: "A single collapsible FAQ-style row. Not a full accordion list — stack multiple instances and control `open` per-instance to build one.",
  props: [
    { name: "title", type: "string", default: "—", description: "The header row's title text." },
    { name: "children", type: "React.ReactNode", default: "—", description: "The answer content, rendered only while open." },
    { name: "open", type: "boolean", default: "—", description: "Whether the answer is expanded." },
    { name: "onToggle", type: "(open: boolean) => void", default: "—", description: "Fires with the new open value when the header is clicked." },
    { name: "disabled", type: "boolean", default: "false", description: "Non-interactive, dimmed background/border." },
  ],
  example: `<AccordionItem title="What is Latent?" open={openId === "1"} onToggle={(open) => setOpenId(open ? "1" : null)}>A proof-of-concept design system.</AccordionItem>`,
  doNot: [
    "Don't render AccordionItem as a standalone list component — it's one row; map over your data and render one instance per row, tracking which id is open yourself.",
  ],
  swizzlePath: "packages/core/src/AccordionItem.tsx",
  figmaTokens: {
    "container padding/gap": "spacing.16",
    "container background": "color.background.default",
    "container border (default)": "color.border.default",
    "container border (hover)": "color.border.strong",
    "container border (focus-within)": "color.border.brand",
    "container background (disabled)": "color.background.subtle",
    "container border (disabled)": "color.border.subtle",
    "container border-radius": "radius.lg",
    "header/answer gap": "spacing.8",
    "title color": "color.text.primary",
    "title font-family": "font-family.sans",
    "title font-size": "font-size.300",
    "title font-weight": "font-weight.600",
    "chevron color": "color.icon.default",
    "answer text color": "color.text.primary",
    "answer font-size": "font-style.body",
  },
};
