export default {
  name: "Calendar",
  summary: "A date-picker grid with month/year navigation. Controlled — the consumer owns month/year/selection state.",
  props: [
    { name: "month", type: "number", default: "—", description: "0-11, matching Date#getMonth()." },
    { name: "year", type: "number", default: "—", description: "Full year, e.g. 2025." },
    { name: "selectedDays", type: "number[]", default: "[]", description: "Day-of-month numbers (current month only) rendered in the Active (selected) state." },
    { name: "rangeDays", type: "number[]", default: "[]", description: "Day-of-month numbers (current month only) rendered in the Range (in-range highlight) state." },
    { name: "disabledDays", type: "number[]", default: "[]", description: "Day-of-month numbers (current month only) rendered Disabled (non-interactive)." },
    { name: "yearOptions", type: "number[]", default: "10 years centered on `year`", description: "Options populating the year <select>." },
    { name: "onSelectDay", type: "(day: number) => void", default: "undefined", description: "Fires when a current-month day is clicked. Adjacent-month (hidden) days are non-interactive." },
    { name: "onPrevMonth", type: "() => void", default: "undefined", description: "Fires when the previous-month nav button is clicked." },
    { name: "onNextMonth", type: "() => void", default: "undefined", description: "Fires when the next-month nav button is clicked." },
    { name: "onMonthChange", type: "(month: number) => void", default: "undefined", description: "Fires when the month <select> changes." },
    { name: "onYearChange", type: "(year: number) => void", default: "undefined", description: "Fires when the year <select> changes." },
  ],
  example: `<Calendar month={8} year={2025} selectedDays={[9, 13]} rangeDays={[10, 11, 12]} onSelectDay={handleSelect} onPrevMonth={handlePrev} onNextMonth={handleNext} onMonthChange={setMonth} onYearChange={setYear} />`,
  doNot: [
    "Don't compute the day grid yourself — pass month/year and let Calendar derive weeks (including adjacent-month padding) internally.",
    "Don't hardcode colors/spacing in overrides; add or reuse a --lat-* custom property instead.",
  ],
  swizzlePath: "packages/core/src/Calendar.tsx",
  // The Calendar Day states in Figma (Default/Hover/Active/Hidden/Disabled/
  // Range/Range Disabled) map to CSS pseudo-classes and modifier classes
  // here rather than separate components — see Calendar.css.
  figmaTokens: {
    "container padding/gap": "spacing.16",
    "container background": "color.background.default",
    "container border": "color.border.subtle",
    "container border-radius": "radius.card",
    "header gap / select-group gap": "spacing.8",
    "nav-button padding": "spacing.8",
    "nav-button border": "color.border.brand",
    "nav-button border-radius": "radius.input",
    "nav-button hover background": "color.action.secondary.hover",
    "nav-button icon color": "color.icon.default",
    "select padding (horizontal)": "spacing.8",
    "select border": "color.border.default",
    "select border-radius": "radius.input",
    "select font-size": "typography.input.value.font-size.sm",
    "select line-height": "typography.input.value.line-height.sm",
    "body/grid gap": "spacing.4",
    "weekday text color": "color.text.tertiary",
    "weekday font-size": "font-size.200",
    "day border-radius": "radius.full",
    "day font-size": "font-size.200",
    "day text color (default)": "color.text.primary",
    "day hover background": "color.background.muted",
    "day active background": "color.action.primary.default",
    "day active text color": "color.text.on-brand",
    "day range background": "color.background.subtle",
    "day disabled text color": "color.text.disabled",
    "day hidden text color": "color.text.tertiary",
    "focus ring color": "color.border.focus",
    "focus ring width": "sizing.border.thin",
    "focus ring offset": "sizing.focus-ring-offset",
  },
};
