export default {
  name: "ChatInput",
  summary: "A message composer bar for AI chat interfaces. Used as the input row inside ChatWindow.",
  props: [
    { name: "value", type: "string", default: "—", description: "The composer field's current text. Controlled — this component holds no internal state." },
    { name: "onChange", type: "(value: string) => void", default: "—", description: "Fires on every keystroke with the field's new text." },
    { name: "onSubmit", type: "() => void", default: "undefined", description: "Fires on Enter or clicking the send button." },
    { name: "onAttach", type: "() => void", default: "undefined", description: "Fires when the leading attach (+) button is clicked." },
    { name: "placeholder", type: "string", default: '"Message Latent..."', description: "Placeholder text shown when value is empty." },
  ],
  example: `<ChatInput value={message} onChange={setMessage} onSubmit={sendMessage} />`,
  doNot: [
    "The send button's active (non-empty value) color isn't a documented Figma state — it's an app-requested affordance reusing color.action.primary.default, not a verified spec value.",
  ],
  swizzlePath: "packages/core/src/ChatInput.tsx",
  extends: null,
  figmaTokens: {
    "container padding": "spacing.2",
    "container gap": "spacing.8",
    "container background": "color.background.default",
    "container border-radius": "radius.lg",
    "attach background": "color.action.secondary.default",
    "attach/send border-radius": "radius.slimlg",
    "attach icon color": "color.icon.default",
    "field text color": "color.text.primary",
    "field placeholder color": "color.text.tertiary",
    "field font-family": "font-family.sans",
    "field font-size": "font-style.body",
    "send background": "color.background.inverse",
    "send background (active, has value)": "color.action.primary.default",
    "send icon color": "color.icon.inverse",
  },
};
