export default {
  name: "NavItem",
  summary: "The atomic row used inside Side Nav's expanded nav list and as Nav Dropdown's trigger.",
  props: [
    { name: "label", type: "string", default: "—", description: "The row's text. Hidden (but still used as the accessible name via aria-label) when iconOnly is true." },
    { name: "selected", type: "boolean", default: "false", description: "Applies the selected background/label styling for the current-page/active-item state." },
    { name: "showIcon", type: "boolean", default: "true", description: "Toggles the leading icon, when one is passed via `icon`." },
    { name: "icon", type: "React.ReactNode", default: "undefined", description: "e.g. <Icon name=\"layout-dashboard\" />, shown leading the label when showIcon is true." },
    { name: "showChevron", type: "boolean", default: "true", description: "Toggles the trailing chevron. Has no effect when iconOnly is true (chevron never renders in that mode)." },
    { name: "chevronName", type: "string", default: '"chevron-down"', description: "Nav Dropdown flips this to \"chevron-up\" based on its own expanded state." },
    { name: "iconOnly", type: "boolean", default: "false", description: "Drops the label and chevron, leaving a square icon button — used by Side Nav's Collapsed state. Existing padding squares up on its own once the label's gone." },
    { name: "disabled", type: "boolean", default: "false", description: "Standard HTML disabled." },
  ],
  example: `<NavItem label="Dashboard" icon={<Icon name="layout-dashboard" />} selected onClick={handleClick} />`,
  doNot: [
    "Don't set iconOnly without a meaningful `label` — with iconOnly there's no visible text, and label becomes the button's only accessible name (via aria-label).",
  ],
  swizzlePath: "packages/core/src/NavItem.tsx",
  extends: "React.ButtonHTMLAttributes<HTMLButtonElement>",
  figmaTokens: {
    "padding (vertical)": "spacing.8",
    "padding (horizontal) / gap": "spacing.10",
    "border-radius": "radius.lg",
    "hover background": "color.action.secondary.hover",
    "pressed background": "color.action.secondary.pressed",
    "focus ring color": "color.border.focus",
    "focus ring width": "sizing.border.thin",
    "icon/chevron color": "color.icon.default",
    "label color": "color.text.secondary",
    "label font-family": "font-family.sans",
    "label font-size": "font-style.body",
    "selected background": "color.background.muted",
    "selected label color": "color.text.primary",
    "selected label weight": "font-weight.600",
  },
};
