export default {
  name: "NavItem",
  summary: "The atomic row used inside Side Nav's expanded nav list and as Nav Dropdown's trigger.",
  props: [
    { name: "label", type: "string", default: "—" },
    { name: "selected", type: "boolean", default: "false" },
    { name: "showIcon", type: "boolean", default: "true" },
    { name: "icon", type: "React.ReactNode", default: "undefined" },
    { name: "showChevron", type: "boolean", default: "true" },
    { name: "chevronName", type: "string", default: '"chevron-down"', description: "Nav Dropdown flips this to \"chevron-up\" based on its own expanded state." },
    { name: "iconOnly", type: "boolean", default: "false", description: "Drops the label and chevron, leaving a square icon button — used by Side Nav's Collapsed state. Existing padding squares up on its own once the label's gone." },
    { name: "disabled", type: "boolean", default: "false" },
  ],
  example: `<NavItem label="Dashboard" icon={<Icon name="layout-dashboard" />} selected onClick={handleClick} />`,
  doNot: [],
  swizzlePath: "packages/core/src/NavItem.tsx",
  figmaTokens: {
    "padding (vertical)": "spacing.8",
    "padding (horizontal) / gap": "spacing.10",
    "border-radius": "radius.lg",
    "hover background": "color.action.secondary.hover",
    "pressed background": "color.action.secondary.pressed",
    "focus ring color": "color.border.focus",
    "focus ring width": "sizing.border.thin",
    "icon/chevron color": "color.icon.default",
    "label color": "color.text.secondary",
    "label font-family": "font-family.sans",
    "label font-size": "font-style.body",
    "selected background": "color.background.muted",
    "selected label color": "color.text.primary",
    "selected label weight": "font-weight.600",
  },
};
