export default {
  name: "SideNav",
  summary: "A floating sidebar navigation panel. Expanded shows the full item list; Collapsed tucks everything into a compact brand pill with an expand toggle.",
  props: [
    { name: "collapsed", type: "boolean", default: "false" },
    { name: "brand", type: "string", default: '"Acme Inc."' },
    { name: "logo", type: "React.ReactNode", default: "undefined", description: "Latent's own logo mark isn't a ported component — supply your own brand icon." },
    { name: "showToggleIcon", type: "boolean", default: "true" },
    { name: "onToggleCollapse", type: "() => void", default: "undefined" },
    { name: "footerLabel", type: "string", default: '"Privacy"' },
    { name: "showFooterIcon", type: "boolean", default: "true" },
    { name: "children", type: "React.ReactNode", default: "undefined", description: "Real NavItem / NavDropdown instances, in order. Ignored while collapsed." },
  ],
  example: `<SideNav brand="Acme Inc." collapsed={collapsed} onToggleCollapse={() => setCollapsed(!collapsed)}><NavItem label="Overview" selected /><NavDropdown label="Resources" expanded={open} onToggle={setOpen} subItems={subs} /></SideNav>`,
  doNot: [
    "Don't build the nav list as a data-array prop — compose real NavItem/NavDropdown children directly, matching Figma's own instance-based structure.",
  ],
  swizzlePath: "packages/core/src/SideNav.tsx",
  figmaTokens: {
    "panel background": "color.surface.raised",
    "panel border": "color.border.subtle",
    "panel border-radius": "radius.card",
    "panel shadow": "elevation.lg",
    "expanded padding": "spacing.12",
    "expanded gap": "spacing.4",
    "collapsed padding (horizontal)": "spacing.12",
    "collapsed padding (vertical)": "spacing.8",
    "collapsed gap": "spacing.8",
    "brand color": "color.text.primary",
    "brand font-family": "font-family.sans",
    "brand font-size": "font-style.body",
    "brand font-weight": "font-weight.600",
    "toggle icon color": "color.icon.default",
    "nav list gap": "spacing.2",
    "divider color": "color.border.subtle",
    "footer label color": "color.text.tertiary",
    "footer label font-size": "font-style.body-small",
  },
};
