export default {
  name: "Stat",
  summary: "A compact highlight card for a single number or metric with a supporting label. For landing pages and dashboards.",
  props: [
    { name: "showIcon", type: "boolean", default: "true" },
    { name: "icon", type: "React.ReactNode", default: "undefined", description: "e.g. <Icon name=\"users\" />, shown inside the icon badge when showIcon is true." },
    { name: "value", type: "string", default: "—", description: 'The big number/metric, e.g. "2,400+".' },
    { name: "label", type: "string", default: "—", description: "Supporting caption below the value." },
  ],
  example: `<Stat icon={<Icon name="users" />} value="2,400+" label="Teams building with Latent" />`,
  doNot: [],
  swizzlePath: "packages/core/src/Stat.tsx",
  figmaTokens: {
    "container padding": "spacing.32",
    "container gap": "spacing.8",
    "container background": "color.surface.raised",
    "container border": "color.border.subtle",
    "container border-radius": "radius.card",
    "container shadow": "elevation.sm",
    "icon badge padding": "spacing.12",
    "icon badge background": "color.background.muted",
    "icon badge border-radius": "radius.lg",
    "icon color": "color.icon.default",
    "value color": "color.text.primary",
    "value font-size": "font-style.h1",
    "value font-weight": "font-weight.700",
    "label color": "color.text.secondary",
    "label font-size": "font-style.body",
  },
};
